# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ad6df54c3e66e837e13a91db7fa6dae55a83469a739fd607a2566e673eba7600a3fe3c4c7a4facf174810bd415a16e85047ddf2611ee3980693011045b13f16

test:
  secret_key_base: 06673d9b4912d758479addbfcf1dbbbb15b2cf701ad9f1c42f22dd08239a579017dc0ba672c81908f7659145b3a52b494d55d2e50c5fe226b5f54db896552194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
